name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello, World!"
      - name: Miltiline commands
        run: |
          echo "This is a multiline command"
          echo "It runs multiple lines in a single step"